Ei 355 maj version keycloak
CQEN-QDCE/digital_marketplace pull request #32
Opened 2022-07-29 20:36 UTC by yonepv

2022-08-09 18:23 UTC, PierreJiji requested changes

2022-08-09 18:23 UTC, PierreJiji commented on openshift/templates/marketplace.yaml
> -  required: true
Pourquoi le required a été enlevé ?

2022-08-09 18:23 UTC, PierreJiji commented on openshift/templates/keycloak.yaml
> +  value: https://keycloak-digital-marketplace.apps.exp.openshift.cqen.ca
```suggestion
  value: https://keycloak-project-name.apps.exp.openshift.cqen.ca
```
Il serait préférable de ne pas spécifier le nom du projet et de le laisser générique afin que le développeur puisse le modifier en fonction de son projet.

2022-08-09 18:23 UTC, PierreJiji commented on openshift/templates/marketplace.yaml
> +  value: "https://keycloak-digital-marketplace.apps.exp.openshift.cqen.ca"
```suggestion
  value: "https://keycloak-$(POD_NAMESPACE).${CLUSTER_DOMAIN}"
```

Il serait préférable de faire le url plus dynamique afin que le développeur puisse le modifier en fonction de son projet.

2022-08-09 18:23 UTC, PierreJiji commented on openshift/README.md
> +    | KEYCLOAK_CLIENT | keycloak: login with the credentials secrets in Openshift for keycloak  |  9d1487b9-6b8a-49f6-a1ac-84b4536f894d |
Il ne faut pas ajouté le secret dans un dépôt public, il serait donc préférable de générer un nouveau secret dans keycloak 
```suggestion
    | KEYCLOAK_CLIENT | keycloak: login with the credentials secrets in Openshift for keycloak  |  xxx-xxx-xx-xxxx-xxxxx |
```

2022-08-09 18:23 UTC, PierreJiji commented on openshift/README.md
> +    oc process -f openshift/templates/marketplace.yaml -p KEYCLOAK_URL=<keycloak-url> -p KEYCLOAK_CLIENT_SECRET=<keycloak-client-secret> | oc apply -f -
Il faut passer les paramètres pour le service de messagerie selon ce que je me rappelle

2022-08-09 18:23 UTC, PierreJiji commented on openshift/README.md
> +    oc process -f openshift/templates/app-digmkt-build.yaml -p NAME=dm | oc apply -f -
Il faudrait valider si on a encore besoin d'utiliser cette étape car selon le déploiement que j'avais fait, je n'avais pas besoin de l'utiliser

2022-08-10 20:47 UTC, yonepv commented on openshift/templates/marketplace.yaml
> -  required: true
https://github.com/CQEN-QDCE/digital_marketplace/commit/d9eac02dbee1a71cbda60923cf45a9502b52ea26

2022-08-10 20:47 UTC, yonepv commented on openshift/templates/keycloak.yaml
> +  value: https://keycloak-digital-marketplace.apps.exp.openshift.cqen.ca
https://github.com/CQEN-QDCE/digital_marketplace/commit/d9eac02dbee1a71cbda60923cf45a9502b52ea26

2022-08-10 20:47 UTC, yonepv commented on openshift/templates/marketplace.yaml
> +  value: "https://keycloak-digital-marketplace.apps.exp.openshift.cqen.ca"
https://github.com/CQEN-QDCE/digital_marketplace/commit/d9eac02dbee1a71cbda60923cf45a9502b52ea26

2022-08-10 20:47 UTC, yonepv commented on openshift/README.md
> +    | KEYCLOAK_CLIENT | keycloak: login with the credentials secrets in Openshift for keycloak  |  9d1487b9-6b8a-49f6-a1ac-84b4536f894d |
https://github.com/CQEN-QDCE/digital_marketplace/commit/d9eac02dbee1a71cbda60923cf45a9502b52ea26

2022-08-10 20:47 UTC, yonepv commented on openshift/README.md
> +    oc process -f openshift/templates/marketplace.yaml -p KEYCLOAK_URL=<keycloak-url> -p KEYCLOAK_CLIENT_SECRET=<keycloak-client-secret> | oc apply -f -
https://github.com/CQEN-QDCE/digital_marketplace/commit/d9eac02dbee1a71cbda60923cf45a9502b52ea26

2022-08-10 20:48 UTC, yonepv commented on openshift/README.md
> +    oc process -f openshift/templates/app-digmkt-build.yaml -p NAME=dm | oc apply -f -
https://github.com/CQEN-QDCE/digital_marketplace/commit/d9eac02dbee1a71cbda60923cf45a9502b52ea26

2022-08-11 12:36 UTC, PierreJiji commented on openshift/templates/keycloak.yaml
> +  value: https://keycloak-digital-marketplace.apps.exp.openshift.cqen.ca
CLUSTER_DOMAIN, POD_NAMESPACE, elles ne sont pas déclarées dans cette template, ce n'est pas la même chose que marketplace.yaml
Il faudrait trouver un moyen de les déclarer de la même manière ou de les mettre en code dur, et je préfère la première option, je ne sais pas ce que tu en penses ?

2022-08-11 15:32 UTC, PierreJiji approved these changes

2022-08-11 15:34 UTC, merged